import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from '@react-oauth/google';
import { Toaster } from 'react-hot-toast';
import ClientSideQueryClientProvider from "../../components/ClientSideQueryClientProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientSideQueryClientProvider>
          <GoogleOAuthProvider clientId="664419105178-feqb82cag4lcod0gne8hl4j3gbls79qk.apps.googleusercontent.com">
            {children}
            <Toaster />
          </GoogleOAuthProvider>
        </ClientSideQueryClientProvider>
      </body>
    </html>
  );
}
